version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: my-ts-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped